[package]
name = "wayland-protocol-docs"
version = "0.1.0"
authors = ["Ho-Yon Mak <hoyon.mak@gmail.com>"]

[dependencies]
wayland-protocol-docs-derive = { path = "wayland-protocol-docs-derive" }
askama = "0.7"
xmltree = "0.8"
unindent = "0.1.3"
glob = "0.2"

[build-dependencies]
askama = "0.7"
